import type { MarketProduct } from "../data";
import type { LocalPreferences, LocalReservation, LocalServiceRequest } from "./local-data";

type ServerListing = { id: string; client_id?: string | null; seller_name: string; item_name: string; description?: string; price_krw: number; category: "home" | "kitchen" | "electronics" | "bedding"; condition: "like_new" | "good" | "used" | "clean"; pickup_location: string; status: "active" | "reserved" | "sold" | "hidden" | "deleted"; image_data_url?: string | null; updated_at?: string };
type ServerState = { listings: ServerListing[]; myListings?: ServerListing[]; reservations: Array<Record<string, unknown>>; serviceRequests: Array<Record<string, unknown>>; lifecycle: Array<{ task_id: string; completed: boolean }>; preferences?: Record<string, unknown> | null; serverVersion?: number };
const category: Record<ServerListing["category"], MarketProduct["category"]> = { home: "Home", kitchen: "Kitchen", electronics: "Electronics", bedding: "Bedding" };
const condition: Record<ServerListing["condition"], MarketProduct["condition"]> = { like_new: "likeNew", good: "good", used: "used", clean: "clean" };
export function serverListingToProduct(item: ServerListing): MarketProduct { return { id: item.id, name: item.item_name, description: item.description ?? "", priceKrw: item.price_krw, category: category[item.category], condition: condition[item.condition], pickup: item.pickup_location, seller: item.seller_name, status: item.status === "reserved" ? "Reserved" : "Available", icon: "box", source: "demo", userCreated: true, ownedByCurrentUser: true, serviceStatus: item.status === "reserved" ? "active" : item.status }; }
export async function bootstrapRemote() { const response = await fetch("/api/session/bootstrap", { method: "POST", credentials: "include" }); return response.ok; }
export async function fetchRemoteState() { const response = await fetch("/api/session/state", { credentials: "include" }); if (!response.ok) throw new Error("remote_state_unavailable"); return await response.json() as ServerState; }
export function serverReservationToLocal(item: Record<string, unknown>): LocalReservation | null { if (typeof item.id !== "string" || typeof item.listing_id !== "string" || typeof item.buyer_name !== "string" || !["active", "cancelled", "completed"].includes(String(item.status)) || typeof item.created_at !== "string") return null; return { id: item.id, productId: item.listing_id, buyerName: item.buyer_name, status: item.status as LocalReservation["status"], createdAt: item.created_at, pickupDate: typeof item.pickup_date === "string" ? item.pickup_date : "", pickupStartTime: typeof item.pickup_start_time === "string" ? item.pickup_start_time.slice(0, 5) : "", pickupEndTime: typeof item.pickup_end_time === "string" ? item.pickup_end_time.slice(0, 5) : "", ...(typeof item.cancelled_at === "string" ? { cancelledAt: item.cancelled_at } : {}), ...(typeof item.completed_at === "string" ? { completedAt: item.completed_at } : {}) }; }
export function serverServiceToLocal(item: Record<string, unknown>): LocalServiceRequest | null { if (typeof item.id !== "string" || typeof item.service_type !== "string" || typeof item.status !== "string" || typeof item.updated_at !== "string") return null; return { id: item.id, productId: typeof item.listing_id === "string" ? item.listing_id : undefined, taskId: typeof item.task_id === "string" ? item.task_id : undefined, mode: item.service_type as LocalServiceRequest["mode"], status: item.status as LocalServiceRequest["status"], deliveryMethod: typeof item.delivery_method === "string" ? item.delivery_method as LocalServiceRequest["deliveryMethod"] : undefined, origin: typeof item.origin === "string" ? item.origin : undefined, destination: typeof item.destination === "string" ? item.destination : undefined, storageDuration: typeof item.storage_duration === "string" ? item.storage_duration as LocalServiceRequest["storageDuration"] : undefined, storageLocation: typeof item.storage_location === "string" ? item.storage_location as LocalServiceRequest["storageLocation"] : undefined, estimatedCostLabel: typeof item.estimated_cost_label === "string" ? item.estimated_cost_label : undefined, termsNote: typeof item.terms_note === "string" ? item.terms_note : undefined, createdAt: typeof item.created_at === "string" ? item.created_at : item.updated_at, updatedAt: item.updated_at }; }
export async function importRemoteState(data: { profile: unknown; done: string[]; products: MarketProduct[]; preferences: LocalPreferences; locale: string }) { const response = await fetch("/api/session/state", { method: "PUT", credentials: "include", headers: { "content-type": "application/json", "x-idempotency-key": `migration-${Date.now()}` }, body: JSON.stringify(data) }); if (!response.ok) throw new Error("remote_import_failed"); }
export async function createRemoteListing(product: MarketProduct, sellerName: string) { const response = await fetch("/api/marketplace/listings", { method: "POST", credentials: "include", headers: { "content-type": "application/json", "x-idempotency-key": `listing-${product.id}` }, body: JSON.stringify({ clientId: String(product.id), sellerName, itemName: product.name ?? product.nameKey?.split(".").pop() ?? "Item", description: product.description ?? "", priceKrw: product.priceKrw, category: product.category, condition: product.condition, pickupLocation: product.pickup ?? "KU campus", imageDataUrl: product.imageDataUrl }) }); if (!response.ok) throw new Error("remote_listing_create_failed"); return serverListingToProduct((await response.json()).listing); }
export async function updateRemoteListing(product: MarketProduct, status?: string) { const payload: Record<string, unknown> = { itemName: product.name, description: product.description, priceKrw: product.priceKrw, pickupLocation: product.pickup, imageDataUrl: product.imageDataUrl }; if (status) payload.status = status; const response = await fetch(`/api/marketplace/listings/${encodeURIComponent(String(product.id))}`, { method: "PATCH", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error("remote_listing_update_failed"); return serverListingToProduct((await response.json()).listing); }
export async function deleteRemoteListing(id: string) { const response = await fetch(`/api/marketplace/listings/${encodeURIComponent(id)}`, { method: "DELETE", credentials: "include" }); if (!response.ok) throw new Error("remote_listing_delete_failed"); }
export async function createRemoteReservation(product: MarketProduct, buyerName: string, pickup: Pick<LocalReservation, "pickupDate" | "pickupStartTime" | "pickupEndTime">) { const response = await fetch(`/api/marketplace/listings/${encodeURIComponent(String(product.id))}/reservations`, { method: "POST", credentials: "include", headers: { "content-type": "application/json", "x-idempotency-key": `reservation-${product.id}-${pickup.pickupDate}-${pickup.pickupStartTime}` }, body: JSON.stringify({ buyerName, ...pickup }) }); if (!response.ok) throw new Error("remote_reservation_failed"); return (await response.json()).reservation as Record<string, unknown>; }
export async function updateRemoteReservation(id: string, updates: Record<string, unknown>) { const response = await fetch(`/api/reservations/${encodeURIComponent(id)}`, { method: "PATCH", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify(updates) }); if (!response.ok) throw new Error("remote_reservation_update_failed"); return (await response.json()).reservation as Record<string, unknown>; }
export async function upsertRemoteService(request: LocalServiceRequest) { const response = await fetch("/api/service-requests", { method: "POST", credentials: "include", headers: { "content-type": "application/json", "x-idempotency-key": request.id }, body: JSON.stringify({ idempotencyKey: request.id, listingId: request.productId, taskId: request.taskId, serviceType: request.mode, status: request.status, storageDuration: request.storageDuration, storageLocation: request.storageLocation, deliveryMethod: request.deliveryMethod, origin: request.origin, destination: request.destination, estimatedCostLabel: request.estimatedCostLabel, termsNote: request.termsNote }) }); if (!response.ok) throw new Error("remote_service_request_failed"); return (await response.json()).serviceRequest as Record<string, unknown>; }
export async function updateRemoteLifecycle(taskId: string, completed: boolean) { const response = await fetch("/api/lifecycle/progress", { method: "PUT", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ taskId, completed }) }); if (!response.ok) throw new Error("remote_lifecycle_failed"); }
