import { NextResponse } from "next/server";
import { apiError, text, uuid } from "@/app/lib/server-api";
import { adminBody, audit, requireAdmin, versionOf } from "@/app/lib/admin";

const statuses = new Set(["active", "reserved", "sold", "hidden", "deleted"]);
export async function PATCH(request: Request, context: { params: Promise<{ id: string }> }) {
  const { client, response } = await requireAdmin(request, true); if (response || !client) return response ?? apiError("server_storage_not_configured", 503); const { id } = await context.params; if (!uuid(id)) return apiError("invalid_listing_id", 422); const body = await adminBody(request); if (!body) return apiError("invalid_listing", 422);
  const { data: current } = await client.from("guest_listings").select("*").eq("id", id).maybeSingle(); if (!current) return apiError("listing_not_found", 404); const version = versionOf(body.version); if (version !== null && version !== current.version) return apiError("version_conflict", 409);
  const updates: Record<string, unknown> = { version: current.version + 1, updated_at: new Date().toISOString() }; const itemName = body.itemName === undefined ? undefined : text(body.itemName, 120); const description = body.description === undefined ? undefined : (typeof body.description === "string" && body.description.length <= 2000 ? body.description.trim() : null); const pickup = body.pickupLocation === undefined ? undefined : text(body.pickupLocation, 200); const price = body.priceKrw;
  if (body.itemName !== undefined && !itemName || body.description !== undefined && description === null || body.pickupLocation !== undefined && !pickup || body.priceKrw !== undefined && (!Number.isInteger(price) || Number(price) <= 0 || Number(price) > 100000000)) return apiError("invalid_listing", 422);
  if (itemName) updates.item_name = itemName; if (description !== undefined) updates.description = description; if (pickup) updates.pickup_location = pickup; if (price !== undefined) updates.price_krw = price; if (body.status !== undefined) { if (!statuses.has(String(body.status))) return apiError("invalid_listing_status", 422); updates.status = body.status; updates.availability = body.status === "reserved" ? "reserved" : "available"; }
  const { data, error } = await client.from("guest_listings").update(updates).eq("id", id).eq("version", current.version).select("*").single(); if (error || !data) return apiError("version_conflict", 409); await audit(client, "listing", id, String(body.status) === "deleted" ? "soft_delete" : String(body.status) === "active" && current.status === "deleted" ? "restore" : "update", text(body.deletionReason, 500)); return NextResponse.json({ listing: data });
}
export async function DELETE(request: Request, context: { params: Promise<{ id: string }> }) { const body = new Request(request.url, { method: "PATCH", headers: { "content-type": "application/json", origin: request.headers.get("origin") ?? "" }, body: JSON.stringify({ status: "deleted" }) }); return PATCH(body, context); }
