import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { apiError } from "@/app/lib/server-api";
import { adminBody, audit, requireAdmin } from "@/app/lib/admin";
import { adminListParams, pagination } from "@/app/lib/admin-list";

const statuses = new Set(["active", "inactive", "deleted", "needs_confirmation"]);
export async function GET(request: Request) { const { client, response } = await requireAdmin(request); if (response || !client) return response ?? apiError("server_storage_not_configured", 503); const params = adminListParams(request); let query = client.from("admin_place_overrides").select("*", { count: "exact" }).order("updated_at", { ascending: false }); if (!params.includeDeleted) query = query.neq("status", "deleted"); if (params.status) query = query.eq("status", params.status); if (params.search) query = query.ilike("place_key", `%${params.search}%`); const { data, error, count } = await query.range((params.page - 1) * params.pageSize, params.page * params.pageSize - 1); return error ? apiError("admin_places_load_failed", 502) : NextResponse.json({ placeOverrides: data ?? [], pagination: pagination(params, count) }); }
export async function POST(request: Request) { const { client, response } = await requireAdmin(request, true); if (response || !client) return response ?? apiError("server_storage_not_configured", 503); const body = await adminBody(request); if (!body || typeof body.payload !== "object" || body.payload === null) return apiError("invalid_place", 422); const placeKey = typeof body.placeKey === "string" && /^[A-Za-z0-9:_-]{1,120}$/.test(body.placeKey) ? body.placeKey : `custom-${randomUUID()}`; const status = statuses.has(String(body.status)) ? String(body.status) : "active"; const { data, error } = await client.from("admin_place_overrides").insert({ place_key: placeKey, base_place_id: typeof body.basePlaceId === "number" ? body.basePlaceId : null, payload: body.payload, status }).select("*").single(); if (error || !data) return apiError(error?.code === "23505" ? "place_duplicate" : "admin_place_create_failed", error?.code === "23505" ? 409 : 502); await audit(client, "place", placeKey, "create"); return NextResponse.json({ placeOverride: data }, { status: 201 }); }
