export type Bilingual = { en: string; ko: string };
export type OfficialGuidance = {
  recommendedTiming: Bilingual;
  applicationLocation: Bilingual;
  link: { href: string; label: Bilingual };
  lastUpdated: Bilingual;
};
export type Task = { id: string; category: Bilingual; title: Bilingual; description: Bilingual; needs: Bilingual[]; time: string; tip: Bilingual; featured?: boolean; officialGuidance?: OfficialGuidance };
export type ProductCategory = "Home" | "Kitchen" | "Electronics" | "Bedding";
export type ProductIcon = "cooking" | "lamp" | "bed" | "kettle" | "fan" | "box";
export type MarketProduct = { id: number | string; name: Bilingual; price: string; category: ProductCategory; condition: Bilingual; pickup: Bilingual; seller: Bilingual; status: "Available" | "Reserved"; icon: ProductIcon; userCreated?: boolean };

export const tasks: Task[] = [
  { id: "dorm", category: { en: "First Week", ko: "첫째 주" }, title: { en: "Dormitory check-in", ko: "기숙사 체크인" }, description: { en: "Collect your room key and confirm the dormitory rules.", ko: "방 열쇠를 받고 기숙사 생활 규칙을 확인하세요." }, needs: [{ en: "Passport", ko: "여권" }, { en: "Dormitory confirmation", ko: "기숙사 확인서" }], time: "20–30", tip: { en: "Save the dorm manager’s number before your first night.", ko: "첫날 전에 기숙사 관리실 번호를 저장해 두세요." } },
  { id: "residence", category: { en: "First Week", ko: "첫째 주" }, title: { en: "Residence confirmation", ko: "거주지 확인" }, description: { en: "Confirm your current housing details and check which residence document you may need.", ko: "현재 거주 정보를 확인하고 어떤 거주지 증빙이 필요한지 공식 안내에서 확인하세요." }, needs: [{ en: "Current housing details", ko: "현재 거주 정보" }, { en: "Official guidance", ko: "공식 안내" }], time: "10–15", tip: { en: "Check current HiKorea guidance before preparing residence documents.", ko: "거주지 서류를 준비하기 전에 HiKorea의 최신 안내를 확인하세요." } },
  { id: "account", category: { en: "First Week", ko: "첫째 주" }, title: { en: "Activate your KU account", ko: "고려대 계정 활성화" }, description: { en: "Set up your portal, Wi-Fi, and campus email access.", ko: "포털, Wi-Fi, 학교 이메일 사용을 설정하세요." }, needs: [{ en: "Student ID number", ko: "학번" }, { en: "Temporary password", ko: "임시 비밀번호" }], time: "10–15", tip: { en: "Use a password manager—you’ll sign in often.", ko: "자주 로그인하므로 비밀번호 관리 앱을 활용하세요." } },
  { id: "arc", category: { en: "ARC / Visa", ko: "외국인등록 / 비자" }, title: { en: "ARC registration", ko: "외국인등록증 신청" }, description: { en: "Register your stay so you can access banking, mobile plans, and other services.", ko: "은행, 휴대폰 요금제 등 한국의 생활 서비스를 이용하기 위해 체류 등록을 하세요." }, needs: [{ en: "Passport", ko: "여권" }, { en: "Passport photo", ko: "여권 사진" }, { en: "Certificate of enrollment", ko: "재학증명서" }, { en: "Residence document", ko: "거주지 증빙서류" }], time: "30–60", tip: { en: "Book your immigration appointment early. Slots may fill quickly.", ko: "출입국 방문 예약은 일찍 하세요. 예약이 빠르게 마감될 수 있습니다." }, featured: true, officialGuidance: { recommendedTiming: { en: "Check the official HiKorea guidance before applying", ko: "신청 전 HiKorea 공식 안내를 확인하세요" }, applicationLocation: { en: "Check the official HiKorea guidance before applying", ko: "신청 전 HiKorea 공식 안내를 확인하세요" }, link: { href: "https://www.hikorea.go.kr/", label: { en: "HiKorea official website", ko: "HiKorea 공식 홈페이지" } }, lastUpdated: { en: "Check HiKorea for the latest guidance", ko: "최신 정보는 HiKorea에서 확인하세요" } } },
  { id: "sim", category: { en: "Mobile & SIM", ko: "휴대폰 / SIM" }, title: { en: "Get a Korean SIM", ko: "한국 SIM 개통" }, description: { en: "Choose a student-friendly plan for calls, data, and identity verification.", ko: "통화, 데이터, 본인인증에 필요한 학생 친화적 요금제를 선택하세요." }, needs: [{ en: "Passport", ko: "여권" }, { en: "Unlocked phone", ko: "통신사 잠금 해제 휴대폰" }], time: "20–40", tip: { en: "A prepaid plan is easiest before your ARC arrives.", ko: "외국인등록증 발급 전에는 선불 요금제가 편리합니다." } },
  { id: "bank", category: { en: "Banking", ko: "은행" }, title: { en: "Open a bank account", ko: "은행 계좌 개설" }, description: { en: "Set up a local account for rent, transfers, and daily payments.", ko: "월세, 송금, 생활 결제를 위한 국내 계좌를 만드세요." }, needs: [{ en: "Passport", ko: "여권" }, { en: "ARC", ko: "외국인등록증" }, { en: "Enrollment certificate", ko: "재학증명서" }], time: "40–60", tip: { en: "Visit before lunch and ask whether English support is available.", ko: "점심시간 전에 방문하고 영어 상담 가능 여부를 물어보세요." } },
  { id: "courses", category: { en: "Course Registration", ko: "수강신청" }, title: { en: "Confirm your course schedule", ko: "수강 시간표 확인" }, description: { en: "Check enrollment, classrooms, and add/drop deadlines.", ko: "수강 등록, 강의실, 정정 기간 마감일을 확인하세요." }, needs: [{ en: "KU portal access", ko: "고려대 포털 계정" }, { en: "Course plan", ko: "수강 계획" }], time: "20–30", tip: { en: "Keep one backup class ready during add/drop week.", ko: "수강 정정 기간을 위해 예비 과목 하나를 준비하세요." } },
  { id: "campus", category: { en: "Campus Life", ko: "캠퍼스 생활" }, title: { en: "Join the campus orientation", ko: "캠퍼스 오리엔테이션 참여" }, description: { en: "Learn the campus, meet buddies, and find student support desks.", ko: "캠퍼스를 익히고 버디와 학생 지원 창구를 만나보세요." }, needs: [{ en: "Student ID", ko: "학생증" }, { en: "Comfortable shoes", ko: "편한 신발" }], time: "60–90", tip: { en: "Take a photo of the campus map for offline use.", ko: "오프라인에서도 볼 수 있도록 캠퍼스 지도를 촬영하세요." } }
];

export const products: MarketProduct[] = [
  { id: 1, name: { en: "Rice Cooker", ko: "전기밥솥" }, price: "₩20,000", category: "Kitchen", condition: { en: "Good", ko: "양호" }, pickup: { en: "Anam Station, Exit 3", ko: "안암역 3번 출구" }, seller: { en: "Exchange student · Mia", ko: "교환학생 · Mia" }, status: "Available", icon: "cooking" },
  { id: 2, name: { en: "Desk Lamp", ko: "책상 스탠드" }, price: "₩8,000", category: "Home", condition: { en: "Like new", ko: "거의 새 상품" }, pickup: { en: "KU Main Gate", ko: "고려대 정문" }, seller: { en: "KU student · Joon", ko: "고려대 학생 · Joon" }, status: "Available", icon: "lamp" },
  { id: 3, name: { en: "Bedding Set", ko: "침구 세트" }, price: "₩15,000", category: "Bedding", condition: { en: "Clean", ko: "세탁 완료" }, pickup: { en: "CJ International House", ko: "CJ 국제관" }, seller: { en: "Exchange student · Lea", ko: "교환학생 · Lea" }, status: "Reserved", icon: "bed" },
  { id: 4, name: { en: "Electric Kettle", ko: "전기포트" }, price: "₩12,000", category: "Kitchen", condition: { en: "Good", ko: "양호" }, pickup: { en: "Anam Ogeori", ko: "안암오거리" }, seller: { en: "KU student · Min", ko: "고려대 학생 · Min" }, status: "Available", icon: "kettle" },
  { id: 5, name: { en: "Mini Fan", ko: "미니 선풍기" }, price: "₩7,000", category: "Electronics", condition: { en: "Good", ko: "양호" }, pickup: { en: "KU Central Plaza", ko: "고려대 중앙광장" }, seller: { en: "Exchange student · Noah", ko: "교환학생 · Noah" }, status: "Available", icon: "fan" },
  { id: 6, name: { en: "Storage Box Set", ko: "수납 박스 세트" }, price: "₩10,000", category: "Home", condition: { en: "Used", ko: "사용감 있음" }, pickup: { en: "Anam Station, Exit 2", ko: "안암역 2번 출구" }, seller: { en: "KU student · Hana", ko: "고려대 학생 · Hana" }, status: "Available", icon: "box" }
];

export const places = [
  { id: 1, name: { en: "Anam Welcome Clinic · Sample", ko: "안암 웰컴 클리닉 · 샘플" }, category: "Hospital", english: true, location: { en: "Anam-ro area", ko: "안암로 인근" }, distance: "5 min", description: { en: "Demo general clinic listing with an international-student desk.", ko: "외국인 학생 안내 데스크가 있는 데모 일반의원입니다." }, tip: { en: "Bring your passport or ARC when visiting.", ko: "방문할 때 여권 또는 외국인등록증을 지참하세요." } },
  { id: 2, name: { en: "Seongbuk Halal Kitchen · Sample", ko: "성북 할랄 키친 · 샘플" }, category: "Halal", english: true, location: { en: "Near Anam Station", ko: "안암역 인근" }, distance: "7 min", description: { en: "Demo casual restaurant serving clearly labeled halal-friendly meals.", ko: "할랄 친화 메뉴를 명확히 표시하는 데모 캐주얼 식당입니다." }, tip: { en: "Ask staff to confirm current ingredients before ordering.", ko: "주문 전 직원에게 현재 식재료를 확인하세요." } },
  { id: 3, name: { en: "Green Table Anam · Sample", ko: "그린 테이블 안암 · 샘플" }, category: "Vegan", english: true, location: { en: "KU Main Gate area", ko: "고려대 정문 인근" }, distance: "6 min", description: { en: "Demo plant-based lunch spot with simple English menu labels.", ko: "간단한 영어 메뉴 표기가 있는 데모 식물성 식당입니다." }, tip: { en: "Lunch sets usually offer the best value.", ko: "점심 세트 메뉴가 보통 가장 합리적입니다." } },
  { id: 4, name: { en: "Campus Care Pharmacy · Sample", ko: "캠퍼스 케어 약국 · 샘플" }, category: "Pharmacy", english: false, location: { en: "Anam Ogeori", ko: "안암오거리" }, distance: "4 min", description: { en: "Demo pharmacy listing for daily medicine and basic health supplies.", ko: "상비약과 기본 건강용품을 판매하는 데모 약국입니다." }, tip: { en: "Show a translated note with your symptoms and allergies.", ko: "증상과 알레르기를 번역한 메모를 보여주세요." } },
  { id: 5, name: { en: "Study Corner Café · Sample", ko: "스터디 코너 카페 · 샘플" }, category: "Cafe", english: true, location: { en: "KU Side Gate area", ko: "고려대 후문 인근" }, distance: "3 min", description: { en: "Demo quiet café listing with outlets and long shared tables.", ko: "콘센트와 긴 공용 테이블이 있는 데모 조용한 카페입니다." }, tip: { en: "Weekday mornings are usually quieter.", ko: "평일 오전이 비교적 한산합니다." } },
  { id: 6, name: { en: "Anam Global Mart · Sample", ko: "안암 글로벌 마트 · 샘플" }, category: "Grocery", english: false, location: { en: "Anam Station area", ko: "안암역 인근" }, distance: "8 min", description: { en: "Demo grocery listing for international ingredients and dorm basics.", ko: "세계 식재료와 기숙사 생활용품을 다루는 데모 식료품점입니다." }, tip: { en: "Bring a reusable bag; bags may cost extra.", ko: "봉투 비용이 추가될 수 있으니 장바구니를 챙기세요." } }
] as const;
