import type { GuideLocaleCopy, LifeGuideArticle } from "./data";
import type { Locale } from "./i18n";
import { legacyCopy } from "./i18n/legacy-copy";

const article = (value: Omit<LifeGuideArticle, "universityId" | "contentCheckedAt" | "sourceStatus">): LifeGuideArticle => ({
  ...value,
  universityId: "korea-university",
  contentCheckedAt: value.lastVerifiedAt ?? "2026-08-29",
  contentOrigin: value.contentOrigin ?? (value.officialUrl ? "official-guide" : "demo"),
  sourceStatus: value.officialUrl ? "verified" : "unavailable"
});

const expandedLifeGuideArticlesBase: LifeGuideArticle[] = [
  article({ id: "dorm-checkin-steps", category: "housing", title: "Prepare for dormitory check-in", summary: "Organize the notice, arrival window, and items required for your dorm check-in.", content: "Dormitory rules and check-in windows can change by term. Use the latest notice from the university before travelling.", checklist: ["Open the latest dorm notice", "Save check-in hours and location", "Prepare the requested documents"], steps: ["Confirm your assigned building", "Check payment and key instructions", "Record any room condition issues"], cautions: ["Follow the current dormitory notice as the final source"], estimatedMinutes: [20, 35], officialUrl: "https://dorm.korea.ac.kr/", sourceName: "Korea University Dormitory", lastVerifiedAt: "2026-08-29", verificationStatus: "official", relatedTaskIds: ["dorm"], locales: { ko: { title: "기숙사 체크인 준비", summary: "기숙사 공지와 입사 시간, 준비물을 미리 정리하세요.", content: "기숙사 규정과 입사 시간은 학기마다 달라질 수 있으므로 출발 전에 최신 공지를 확인하세요." }, ja: { title: "寮のチェックイン準備", summary: "寮の案内、入室時間、必要な物を整理します。", content: "寮の規則や時間は学期ごとに変わる可能性があるため、最新のお知らせを確認してください。" }, "zh-CN": { title: "准备宿舍入住", summary: "整理宿舍通知、入住时间和所需物品。", content: "宿舍规则和入住时间可能按学期变化，请在出发前确认最新通知。" } } }),
  article({ id: "airport-to-ku", category: "arrival", title: "Travel from the airport to KU", summary: "Compare practical routes from the airport and prepare an offline destination note.", content: "Route times and fares change. Check the official transport operator before leaving the airport.", checklist: ["Write the destination in Korean", "Check the latest route and fare", "Keep a backup taxi plan"], steps: ["Choose rail, bus, or taxi", "Save the transfer points", "Confirm the final walking route"], cautions: ["Allow extra time for transfers and luggage"], estimatedMinutes: [15, 30], officialUrl: "https://english.seoul.go.kr/", sourceName: "Seoul Metropolitan Government", lastVerifiedAt: "2026-08-29", verificationStatus: "official", relatedTaskIds: ["airport-route"], locales: { ko: { title: "공항에서 고려대학교까지 이동", summary: "공항에서 고려대로 이동할 경로와 오프라인 목적지 메모를 준비하세요.", content: "노선 시간과 요금은 바뀔 수 있으므로 출발 전에 공식 교통기관에서 확인하세요." }, ja: { title: "空港から高麗大学へ移動する", summary: "空港からの経路と目的地メモを準備します。", content: "所要時間や運賃は変わるため、出発前に公式交通情報を確認してください。" }, "zh-CN": { title: "从机场前往高丽大学", summary: "比较机场路线并准备离线目的地信息。", content: "路线时间和票价可能变化，请在离开机场前确认官方交通信息。" } } }),
  article({ id: "arc-current-check", category: "immigration", title: "Check current ARC guidance", summary: "Use HiKorea to confirm the documents and appointment rules that apply to your status.", content: "Immigration requirements are status-dependent and can change. Treat this article as a checklist for finding the current official notice.", checklist: ["Confirm your status", "Open the current HiKorea notice", "Prepare only the documents listed there"], steps: ["Search the relevant residence service", "Check the current fee and appointment rule", "Save the official page"], cautions: ["Do not rely on an old checklist"], estimatedMinutes: [20, 40], officialUrl: "https://www.hikorea.go.kr/", sourceName: "HiKorea", lastVerifiedAt: "2026-08-29", verificationStatus: "official", relatedTaskIds: ["arc"], locales: { ko: { title: "ARC 최신 안내 확인", summary: "하이코리아에서 체류 자격에 맞는 서류와 예약 규정을 확인하세요.", content: "출입국 요건은 체류 자격에 따라 달라지고 변경될 수 있습니다. 이 글은 최신 공식 공지를 찾기 위한 체크리스트입니다." }, ja: { title: "ARCの最新案内を確認する", summary: "HiKoreaで自分の在留資格に合う書類と予約規則を確認します。", content: "要件は在留資格により異なり変更される可能性があります。最新の公式案内を確認してください。" }, "zh-CN": { title: "确认ARC最新指南", summary: "在HiKorea确认适用于自己身份的材料和预约规则。", content: "出入境要求可能因身份而异并发生变化，请以最新官方通知为准。" } } }),
  article({ id: "sim-esim-options", category: "mobile-banking", title: "Compare SIM and eSIM options", summary: "Check device compatibility, identity requirements, and current plan terms before purchase.", content: "Plan availability and registration requirements vary by provider. Confirm the current offer directly with the provider.", checklist: ["Check that your phone is unlocked", "Estimate monthly data", "Compare prepaid and monthly terms"], steps: ["Check eSIM compatibility", "Read the current identity requirement", "Save the provider support contact"], cautions: ["This comparison is general guidance, not a provider offer"], estimatedMinutes: [15, 25], verificationStatus: "needs_confirmation", relatedTaskIds: ["sim", "sim-compare"], locales: { ko: { title: "SIM·eSIM 요금제 비교", summary: "구매 전에 기기 호환성, 본인 확인 요건과 현재 요금 조건을 비교하세요.", content: "요금제와 개통 요건은 통신사마다 다르므로 최종 조건은 통신사에서 직접 확인하세요." }, ja: { title: "SIM・eSIMを比較する", summary: "購入前に端末対応、本人確認、料金条件を比較します。", content: "プランや開通条件は事業者により異なるため、最新条件を確認してください。" }, "zh-CN": { title: "比较SIM与eSIM方案", summary: "购买前比较设备兼容性、身份要求和当前套餐条件。", content: "套餐和开通要求因运营商而异，请直接确认最新条件。" } } }),
  article({ id: "ku-portal-basics", category: "academic", title: "Set up access to KU academic systems", summary: "Find the current portal, course registration, timetable, and notice locations.", content: "Academic system menus and dates are controlled by the university. Use current KU notices for deadlines.", checklist: ["Open the KU portal", "Find course registration dates", "Save the academic notice page"], steps: ["Sign in using your existing KU account", "Check timetable and classroom details", "Review notices before each deadline"], cautions: ["Dates can differ by program"], estimatedMinutes: [15, 30], officialUrl: "https://portal.korea.ac.kr/p/PR/", sourceName: "Korea University Portal", lastVerifiedAt: "2026-08-29", verificationStatus: "official", relatedTaskIds: ["account", "courses"], locales: { ko: { title: "고려대학교 학사 시스템 시작하기", summary: "포털, 수강신청, 시간표와 학사 공지 위치를 확인하세요.", content: "학사 시스템 메뉴와 일정은 학교가 관리하므로 마감일은 최신 고려대 공지를 기준으로 확인하세요." }, ja: { title: "高麗大学の学務システムを使い始める", summary: "ポータル、履修登録、時間割、学務のお知らせを確認します。", content: "日程は大学の最新のお知らせを最終基準にしてください。" }, "zh-CN": { title: "开始使用高丽大学学术系统", summary: "确认门户、选课、课表和学术通知的位置。", content: "学术系统和日期由学校管理，请以最新学校通知为准。" } } }),
  article({ id: "emergency-119", category: "healthcare", title: "Know the emergency number 119", summary: "Keep the emergency number and your location ready before an urgent situation happens.", content: "For urgent medical or fire emergencies in Korea, call 119. For non-urgent care, confirm the provider and language support first.", checklist: ["Save 119", "Write your address in Korean", "Keep your passport and insurance information accessible"], steps: ["Call 119 in an emergency", "State your location clearly", "Follow the dispatcher instructions"], cautions: ["Use emergency services for urgent situations"], estimatedMinutes: [5, 10], officialUrl: "https://www.gov.kr/portal/foreigner/ko", sourceName: "Korean Government", verificationStatus: "needs_confirmation", relatedTaskIds: ["healthcare"], locales: { ko: { title: "응급전화 119 알아두기", summary: "긴급 상황에 대비해 119와 현재 위치를 준비해 두세요.", content: "한국에서 긴급한 의료·화재 상황은 119에 신고하세요. 비응급 진료는 기관과 언어 지원을 먼저 확인하세요." }, ja: { title: "緊急電話119を知っておく", summary: "緊急時に備えて119と現在地を準備します。", content: "韓国で緊急の医療・火災の場合は119に連絡してください。" }, "zh-CN": { title: "了解紧急电话119", summary: "提前记住119并准备好自己的位置。", content: "在韩国遇到紧急医疗或火灾情况请拨打119。" } } }),
  article({ id: "recycling-basics", category: "daily", title: "Learn local recycling basics", summary: "Check the building notice for collection days, bags, and sorting rules.", content: "Recycling and food-waste rules vary by district and building. Use the local notice as the final source.", checklist: ["Find the building collection notice", "Separate food waste as instructed", "Buy the required bags if needed"], steps: ["Check the district rule", "Sort containers and labels", "Put items out at the stated time"], cautions: ["Rules vary by neighborhood"], estimatedMinutes: [10, 20], verificationStatus: "needs_confirmation", relatedTaskIds: ["household-essentials"], locales: { ko: { title: "쓰레기 분리배출 기본 확인", summary: "거주 건물의 배출 요일과 봉투, 분류 규정을 확인하세요.", content: "분리배출과 음식물 쓰레기 규정은 지역과 건물마다 다를 수 있으므로 현장 안내를 최종 기준으로 삼으세요." }, ja: { title: "ごみ分別の基本を確認する", summary: "建物の収集日、袋、分別ルールを確認します。", content: "ルールは地域や建物により異なるため、現地の案内を確認してください。" }, "zh-CN": { title: "了解垃圾分类基础", summary: "确认住所的收集日、垃圾袋和分类规则。", content: "规则可能因地区和建筑而异，请以当地通知为准。" } } }),
  article({ id: "departure-shipping", category: "departure", title: "Plan shipping and move-out", summary: "Organize sales, storage, shipping, and housing handover before departure.", content: "Provider prices and customs rules can change. Compare current terms and keep receipts for important shipments.", checklist: ["List items to sell or ship", "Confirm housing handover date", "Check airline baggage limits"], steps: ["Choose keep, sell, donate, or ship", "Measure and pack items", "Record tracking and handover details"], cautions: ["Confirm international shipping restrictions before payment"], estimatedMinutes: [30, 60], verificationStatus: "demo", relatedTaskIds: ["sell-items", "luggage", "departure-checklist"], locales: { ko: { title: "귀국 전 배송과 퇴실 계획", summary: "판매·보관·배송과 주거 인계를 귀국 전에 정리하세요.", content: "배송 요금과 통관 규정은 바뀔 수 있으므로 현재 조건을 비교하고 중요한 발송 영수증을 보관하세요." }, ja: { title: "帰国前の配送と退去を計画する", summary: "販売、保管、配送、住居の引き渡しを整理します。", content: "料金や通関規則は変わるため、最新条件を確認してください。" }, "zh-CN": { title: "规划回国前的寄送与退房", summary: "在回国前整理出售、寄存、寄送和住房交接。", content: "运费和海关规则可能变化，请确认当前条件并保存重要收据。" } } })
];

export const expandedLifeGuideArticles: LifeGuideArticle[] = expandedLifeGuideArticlesBase.map((item) => {
  const overrides: Partial<LifeGuideArticle> = {
    contentCheckedAt: "2026-08-29",
    contentOrigin: item.contentOrigin ?? (item.officialUrl ? "official-guide" : "demo"),
    sourceStatus: item.officialUrl ? "verified" : "unavailable"
  };
  if (item.id === "sim-esim-options") Object.assign(overrides, { officialUrl: "https://english.seoul.go.kr/service/living/convenience/3-communication/", sourceName: "Seoul Metropolitan Government", contentOrigin: "official-guide" as const, sourceStatus: "verified" as const, verificationStatus: "official" as const });
  if (item.id === "recycling-basics") Object.assign(overrides, { officialUrl: "https://news.seoul.go.kr/env/archives/507225", sourceName: "Seoul Metropolitan Government", contentOrigin: "official-guide" as const, sourceStatus: "verified" as const, verificationStatus: "verified" as const });
  if (item.id === "departure-shipping") Object.assign(overrides, { officialUrl: "https://www.koreapost.go.kr/eng/subIndex/4418.do", sourceName: "Korea Post", contentOrigin: "official-guide" as const, sourceStatus: "verified" as const, verificationStatus: "verified" as const });
  if (item.id === "emergency-119") Object.assign(overrides, { sourceStatus: "verified" as const, verificationStatus: "verified" as const });
  return { ...item, ...overrides };
});

type GuideSections = { checklist: string[]; steps?: string[]; cautions?: string[] };
type LocalizedSections = Partial<Record<Locale, GuideSections>>;
const section = (checklist: string[], steps?: string[], cautions?: string[]): GuideSections => ({ checklist, steps, cautions });

const localizedSections: Record<string, LocalizedSections> = {
  "ku-dorm-guide": { ko: section(["내 과정에 적용되는 페이지 확인", "최신 공지와 필요한 서류 확인", "공식 페이지 저장"], ["대상 과정 확인", "최신 일정과 서류 확인", "필요한 내용을 저장"], ["최종 기준은 현재 기숙사 공지입니다."]), ja: section(["自分のプログラムに適用されるページを確認", "最新のお知らせと必要書類を確認", "公式ページを保存"], ["対象プログラムを確認", "最新の日程と書類を確認", "必要な情報を保存"], ["最新の寮のお知らせを最終基準にしてください。"]), "zh-CN": section(["确认适用于自己项目的页面", "确认最新通知和所需材料", "保存官方页面"], ["确认适用项目", "确认最新日期和材料", "保存所需信息"], ["请以当前宿舍通知为最终依据。"]) },
  "hikorea-residence": { ko: section(["현재 체류 자격 확인", "공식 공지 확인", "담당 기관에 문의"], ["관련 체류 서비스 검색", "현재 수수료와 예약 규정 확인", "공식 페이지 저장"], ["공지가 불명확하면 담당 기관에 확인하세요."]), ja: section(["現在の在留資格を確認", "公式のお知らせを確認", "担当機関に問い合わせ"], ["該当する在留サービスを検索", "現在の手数料と予約規則を確認", "公式ページを保存"], ["不明な場合は担当機関に確認してください。"]), "zh-CN": section(["确认当前居留身份", "确认官方通知", "咨询负责机构"], ["搜索相关居留服务", "确认当前费用和预约规则", "保存官方页面"], ["通知不清楚时请向负责机构确认。"]) },
  "transit-card-basics": { ko: section(["공식 운영기관에서 노선 확인", "요금과 결제 방법 확인", "환승 시간 여유 두기"], ["노선 선택", "환승 지점 저장", "최종 도보 경로 확인"], ["환승과 짐을 고려해 여유 있게 이동하세요."]), ja: section(["公式運営機関で路線を確認", "運賃と支払い方法を確認", "乗り換え時間に余裕を持つ"], ["経路を選ぶ", "乗り換え地点を保存", "最後の徒歩経路を確認"], ["乗り換えと荷物のため時間に余裕を持ってください。"]), "zh-CN": section(["在官方运营机构确认路线", "确认票价和支付方式", "预留换乘时间"], ["选择路线", "保存换乘地点", "确认最后步行路线"], ["请考虑换乘和行李，预留充足时间。"]) },
  "dorm-checkin-steps": { ko: section(["최신 기숙사 공지 열기", "입사 시간과 장소 저장", "요청된 서류 준비"], ["배정 건물 확인", "납부와 열쇠 안내 확인", "방 상태 문제 기록"], ["최신 기숙사 공지를 최종 기준으로 따르세요."]), ja: section(["最新の寮のお知らせを開く", "入室時間と場所を保存", "必要書類を準備"], ["割り当てられた建物を確認", "支払いと鍵の案内を確認", "部屋の状態を記録"], ["最新の寮のお知らせを最終基準にしてください。"]), "zh-CN": section(["打开最新宿舍通知", "保存入住时间和地点", "准备所需材料"], ["确认分配的楼栋", "确认付款和钥匙说明", "记录房间状况"], ["请以最新宿舍通知为最终依据。"]) },
  "airport-to-ku": { ko: section(["목적지를 한국어로 적기", "최신 노선과 요금 확인", "택시 대안 준비"], ["철도·버스·택시 선택", "환승 지점 저장", "최종 도보 경로 확인"], ["환승과 수하물을 고려해 시간을 넉넉히 잡으세요."]), ja: section(["目的地を韓国語で書く", "最新の経路と運賃を確認", "タクシーの代替案を準備"], ["鉄道・バス・タクシーを選ぶ", "乗り換え地点を保存", "最後の徒歩経路を確認"], ["乗り換えと荷物を考慮して時間に余裕を持ってください。"]), "zh-CN": section(["用韩文写下目的地", "确认最新路线和票价", "准备出租车备用方案"], ["选择铁路、公交或出租车", "保存换乘地点", "确认最后步行路线"], ["请考虑换乘和行李，预留充足时间。"]) },
  "arc-current-check": { ko: section(["현재 체류 자격 확인", "최신 하이코리아 공지 열기", "공지에 적힌 서류만 준비"], ["관련 체류 서비스 검색", "현재 수수료와 예약 규정 확인", "공식 페이지 저장"], ["오래된 체크리스트에 의존하지 마세요."]), ja: section(["現在の在留資格を確認", "最新のHiKoreaのお知らせを開く", "記載された書類だけを準備"], ["該当する在留サービスを検索", "現在の手数料と予約規則を確認", "公式ページを保存"], ["古いチェックリストに頼らないでください。"]), "zh-CN": section(["确认当前居留身份", "打开最新HiKorea通知", "只准备通知中列出的材料"], ["搜索相关居留服务", "确认当前费用和预约规则", "保存官方页面"], ["不要依赖过时的清单。"]) },
  "sim-esim-options": { ko: section(["휴대전화 잠금 해제 여부 확인", "월 데이터 사용량 예상", "선불·월정액 조건 비교"], ["eSIM 호환성 확인", "현재 본인 확인 요건 확인", "저렴한 통신사 지원 창구 저장"], ["이 비교는 일반 안내이며 특정 통신사 상품을 보증하지 않습니다."]), ja: section(["端末のSIMロックを確認", "月間データ量を見積もる", "プリペイドと月額条件を比較"], ["eSIM対応を確認", "現在の本人確認要件を確認", "事業者のサポート窓口を保存"], ["一般的な案内であり、特定事業者の商品を保証するものではありません。"]), "zh-CN": section(["确认手机是否已解锁", "估算每月数据量", "比较预付费和月租条件"], ["确认eSIM兼容性", "确认当前身份验证要求", "保存运营商支持联系方式"], ["这是一般指南，不代表任何运营商的具体产品。 "]) },
  "ku-portal-basics": { ko: section(["고려대 포털 열기", "수강신청 일정 찾기", "학사 공지 페이지 저장"], ["기존 고려대 계정으로 로그인", "시간표와 강의실 확인", "마감 전 공지 확인"], ["일정은 과정에 따라 다를 수 있습니다."]), ja: section(["KUポータルを開く", "履修登録日程を探す", "学務のお知らせを保存"], ["既存のKUアカウントでログイン", "時間割と教室を確認", "締切前にお知らせを確認"], ["日程はプログラムにより異なる場合があります。"]), "zh-CN": section(["打开KU门户", "查找选课日期", "保存学术通知页面"], ["使用已有KU账户登录", "确认课表和教室", "在截止日期前查看通知"], ["日期可能因项目而异。 "]) },
  "emergency-119": { ko: section(["119 저장", "한국어 주소 적어두기", "여권과 보험 정보 준비"], ["응급 상황에서 119 신고", "위치를 정확히 말하기", "구조대 안내 따르기"], ["긴급 상황에만 응급 서비스를 이용하세요."]), ja: section(["119を保存", "住所を韓国語で書く", "パスポートと保険情報を準備"], ["緊急時に119へ電話", "場所を正確に伝える", "指令員の指示に従う"], ["緊急時に救急サービスを利用してください。"]), "zh-CN": section(["保存119", "用韩文写下地址", "准备护照和保险信息"], ["紧急时拨打119", "清楚说明位置", "遵循调度员指示"], ["仅在紧急情况下使用急救服务。 "]) },
  "recycling-basics": { ko: section(["건물 배출 안내 확인", "안내에 따라 음식물 분리", "필요하면 지정 봉투 구매"], ["자치구 규정 확인", "용기와 라벨 분류", "지정된 시간에 배출"], ["규정은 동네마다 다를 수 있습니다."]), ja: section(["建物の収集案内を確認", "案内に従って生ごみを分別", "必要なら指定袋を購入"], ["区のルールを確認", "容器とラベルを分ける", "指定時間に出す"], ["ルールは地域により異なります。"]), "zh-CN": section(["查找楼栋收集通知", "按说明分类厨余垃圾", "需要时购买指定垃圾袋"], ["确认区级规定", "分类容器和标签", "在规定时间投放"], ["规则可能因社区而异。 "]) },
  "departure-shipping": { ko: section(["판매·배송할 물품 목록 작성", "주거 인계일 확인", "항공 수하물 한도 확인"], ["보관·판매·기부·배송으로 분류", "물품 크기 측정과 포장", "운송장과 인계 내용 기록"], ["결제 전에 국제 배송 제한을 확인하세요."]), ja: section(["販売・発送する品物を一覧化", "住居の引き渡し日を確認", "航空手荷物の制限を確認"], ["保管・販売・寄付・発送に分類", "大きさを測って梱包", "追跡番号と引き渡し内容を記録"], ["支払い前に国際配送の制限を確認してください。"]), "zh-CN": section(["列出要出售或寄送的物品", "确认住房交接日期", "确认航空行李限额"], ["分类保留、出售、捐赠或寄送", "测量并包装物品", "记录追踪号和交接信息"], ["付款前请确认国际寄送限制。 "]) }
};

export function getGuideLocaleCopy(article: LifeGuideArticle, locale: Locale): GuideLocaleCopy {
  const base = (article.locales as Record<string, GuideLocaleCopy | undefined>)[locale]
    ?? legacyCopy(locale, { title: article.title, summary: article.summary, content: article.content });
  const translated = localizedSections[article.id]?.[locale];
  const fallbackSections = legacyCopy(locale, { checklist: article.checklist, steps: article.steps, cautions: article.cautions });
  return { ...base, checklist: translated?.checklist ?? fallbackSections.checklist, steps: translated?.steps ?? fallbackSections.steps, cautions: translated?.cautions ?? fallbackSections.cautions };
}
