import { NextResponse } from "next/server";
import { randomUUID } from "node:crypto";
import { apiError, jsonBody, record, text } from "@/app/lib/server-api";
import { getOrCreateServerSession, requireSameOrigin, serverClient } from "@/app/lib/server-session";
import { notifySession } from "@/app/lib/notifications";
import { consumeSupportRefetchFailure } from "@/app/lib/integration-fault";

export async function GET() { const session = await getOrCreateServerSession(); const client = serverClient(); if (!session || !client) return apiError("session_unavailable", 503); if (consumeSupportRefetchFailure(session.id)) return apiError("tickets_load_failed", 502); const { data, error } = await client.from("support_tickets").select("id,reference_code,subject,body,status,operator_response,handled_at,created_at,updated_at").eq("session_id", session.id).neq("status", "deleted").order("updated_at", { ascending: false }); return error ? apiError("tickets_load_failed", 502) : NextResponse.json({ tickets: data ?? [] }, { headers: { "Cache-Control": "no-store" } }); }
export async function POST(request: Request) { if (!await requireSameOrigin(request)) return apiError("invalid_origin", 403); const session = await getOrCreateServerSession(); const client = serverClient(); if (!session || !client) return apiError("session_unavailable", 503); const body = await jsonBody(request); const subject = record(body) ? text(body.subject, 160) : null; const message = record(body) ? text(body.body, 3000) : null; if (!subject || !message) return apiError("invalid_ticket", 422); const referenceCode = `TKT-${randomUUID().replaceAll("-", "").slice(0, 8).toUpperCase()}`; const { data, error } = await client.from("support_tickets").insert({ session_id: session.id, reference_code: referenceCode, subject, body: message, status: "reviewing" }).select("id,reference_code,subject,status,created_at").single(); if (error || !data) return apiError("ticket_create_failed", 502); await notifySession(client, session.id, "support_ticket_created", "운영 문의가 접수되었습니다", "문의가 접수되었습니다. 처리 상태와 운영자 답변은 앱에서 확인하세요.", "support_ticket", data.id); return NextResponse.json({ ticket: data }, { status: 201, headers: { "Cache-Control": "no-store" } }); }
